### ISSUE TITLE
Various editorial from Jim

### ISSUE THREAD

**Issue by cabo** [cbor-wg/array-tags#10]
@jschaad notes:

1.  In section 2.1 I had a brief moment of frisson on the use of the term binary16 rather than float16 in Table 1.  There is no need to change it, I just was momentarily jolted.

2.  In section 2.1 - Slightly odd to say that ll is lsb as it is two bits long.  No need to change it, but the RSE may notice it.

3.  In section 2.1 - suggest s/Only the big endian variant is used./Only the big endian variant is assigned a tag./

4. In section 2.1 - There should be a note about the fate of the tags that would be <float, signed>.  Are they reserved or open for assignment.

5. In section 2.1 - After reading the last sentence, I am no longer sure what the fate of the 8-bit little endian tags are.  It would appear that they are being assigned from this paragraph.

6. In section 3 - It would make thing clearer if the description here noted that Homogeneous Arrays are one-dimensional array.

**Comment by jimsch** [comment]
1 - No change requested.
2 - Looks fine
3 - currently no change
4 - currently no change
5 - Looks fine
6 - Looks fine
