### ISSUE TITLE
use case for clamped arrays

### ISSUE THREAD

**Issue by cabo** [cbor-wg/array-tags#6]
jyasskin notes that 6. It's not clear to me that representing the source of the elements
in a uint8 array is worth the confusion of re-using the
is-little-endian bit. What's a use case? It exists in Javascript to
define how assignment works, but one does not assign to CBOR data.

**Comment by jyasskin** [comment]
I don't think #12 gave a solid use case for clamped arrays. We now [have](https://cbor-wg.github.io/array-tags/draft-ietf-cbor-array-tags.html#dataTypes):

> As a special case, the Tag that would signify the little endian variant of uint8 is instead assigned to signify that the numbers in the array are using clamped conversion from integers, as described in more detail in Section 7.1.11 (ToUint8Clamp) of the ES6 JavaScript specification {{TypedArrayES6}}; the assumption here is that a program-internal representation of this array after decoding would be marked this way for further processing, providing "roundtripping" of JavaScript typed arrays through CBOR.

This seems to say that a program should allow the entity that's sending it data to also choose how that data is processed inside the program. That seems like a recipe for security problems. Even if the WG wants to define a way for the sender to suggest the recipient's behavior when future computations overflow, I think that should be separate from the typed array tags, which a naive reader might assume are just for optimizing the wire representation.

**Comment by cabo** [comment]
> 
> This seems to say that a program should allow the entity that's sending it data to also choose how that data is processed inside the program. That seems like a recipe for security problems.

It would be if the sender had a free choice here.  

I still think the roundtripping of ES6 typed arrays is worth this little complication.

> Even if the WG wants to define a way for the sender to suggest the recipient’s behavior when future computations overflow, I think that should be separate from the typed array tags, which a naive reader might assume are just for optimizing the wire representation.

For me this is a small wart of the TypedArray spec, which I think we’d better cover completely instead of taking out one case.

Grüße, Carsten
