### ISSUE TITLE
use case for homogeneous arrays

### ISSUE THREAD

**Issue by cabo** [cbor-wg/array-tags#7]
@jyasskin asks 7. What's the use case for the homogenous array tag? Tags, in general,
are mostly useful for generic parsers: do we have an example of one of
those that's going to add a new set of homogenous array types for its
consumers to have to check for?

**Comment by cabo** [comment]
I believe this question is already answered by the first paragraph of section 3.2 (as well as the last sentence of the intro for 3).  I'm not sure what else should be said.

**Comment by jyasskin** [comment]
I see 

> The Homogeneous Array tag can be used to facilitate the ingestion of homogeneous classical CBOR arrays, providing performance advantages even when a Typed Array does not apply.
> ...
> This can be used by implementations in strongly typed languages while decoding to create native homogeneous arrays of specific types instead of ordered lists.
>
> Which CBOR data items constitute elements of the same application type is specific to the application.

That last sentence seems to indicate that a generic parser can't be expected to figure out from the first element of an array which native type it needs to create an array of. If generic parsers can't take advantage of this, and application specific ones, of course, already know what types to expect and don't need a tag to tell them, then there don't seem to be any use cases left.

**Comment by jimsch** [comment]
Example:

typedef struct {
  bool active;
  union {
      int value;
      bool b;
      double d;
  };
} foo;

foo myArray[2] = { {true, 3}, {true, false} }

<Tag 41>
  82 # array(2)
    82  # array(2)
      F5 # true
      03 # 3
    82 # array(2)
      F5 # true
      F4 # false

There is no reason for a generic parser to think that this is really homogeneous even if a higher level parser does.
